language: python
python:
  - "3.5"
env:
  global:
    - PIP_DOWNLOAD_CACHE=$HOME/.pip_cache
  matrix:
    - TOX_ENV=py27
    - TOX_ENV=py34
    - TOX_ENV=py35
    - TOX_ENV=flake8
cache:
  directories:
    - $HOME/.pip-cache/
install:
  - "travis_retry pip install setuptools --upgrade"
  - "travis_retry pip install tox"
script:
  - tox -e $TOX_ENV
after_script:
  - cat .tox/$TOX_ENV/log/*.log
